# version: '3.7'

# services:
  # jenkins:
    # image: jenkins/jenkins:lts
    # container_name: jenkins
    # restart: always
    # ports:
      # - "8090:8080"  # Web interface
      # - "50000:50000"  # For Jenkins agents
    # volumes:
      # - jenkins_home:/var/jenkins_home
    # networks:
      # - jenkins_network

# volumes:
  # jenkins_home: D:\DockerAirflow\jenkin

# networks:
  # jenkins_network:
    # driver: bridge

# --
version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8090:8080"  # Web interface
      - "50000:50000"  # For Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home  # Use the named volume defined below
    networks:
      - jenkins_network

volumes:
  jenkins_home:
    driver: local
    driver_opts:
      type: none
      device: D:\DockerAirflow\jenkin\jenkins_home  # Host path on Windows
      o: bind

networks:
  jenkins_network:
    driver: bridge
